services:
  postgres:
    image: postgres
    container_name: image-cropper-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_cropper_db
    ports:
      - "5433:5432"

  backend:
    build: ./server
    container_name: image-cropper-backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/image_cropper_db
      AUTH0_DOMAIN: dev-z8ecymffamlxli4p.us.auth0.com
      AUTH0_AUDIENCE: https://image-cropper-api
    command: sh -c "npx wait-on tcp:postgres:5432 && npx prisma migrate deploy && npm run dev"
    depends_on:
      - postgres

  frontend:
    build: ./client
    container_name: image-cropper-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_AUTH0_DOMAIN: dev-z8ecymffamlxli4p.us.auth0.com
      VITE_AUTH0_CLIENT_ID: wBPm0nmlRSuvUjnr8QWZlI7mvc4NVdSR
      VITE_AUTH0_AUDIENCE: https://image-cropper-api
    depends_on:
      - backend
